#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 13 16:17:28 2018

@author: waterwoo
"""

password_list = ['*#*#', '12345']

def account_login():
    password = input('Password:')
    password_reset = password == password_list[0]
    password_correct = password == password_list[-1]

    if password_correct:
        print('Login success!')
        
    elif password_reset:
        password_list[-1] = input('Please input your new password:')
        print('password has been reset')
    
    else:
        print('Wrong password or invalid input!')
        account_login()
account_login()
